@startuml
' Définition des styles pour une meilleure lisibilité
skinparam componentStyle rectangle
skinparam rectangle {
  BackgroundColor #F9F9F9
  BorderColor #333333
}

' Composants principaux
component "Frontend Web/App\n(Angular, React, ...)" as Frontend
component "Microservice \nSpring Boot (Java) pour les produits" as SpringBootProducts
component "Microservice \nSpring Boot (Java) pour le paiement des produits" as SpringBootPaymentProducts
database "Base de données des produits\n(MySQL, PostgreSQL...)" as DB_products
database "Base de données du paiement des produits\n(MySQL, PostgreSQL...)" as DB_payment_products

' Flux de communication
Frontend -[#blue]-> SpringBootProducts : API REST(CRUD)\n(HTTP)\n localhost:8082
Frontend -[#blue]-> SpringBootPaymentProducts : API REST(CRUD)\n(HTTP)\n localhost:8081
SpringBootPaymentProducts -[#orange]-> SpringBootProducts : API REST (ReadUpdate) \n(HTTP)\n localhost:8082
SpringBootProducts -[#green]-> DB_products : JPA/ORM (CRUD)
SpringBootPaymentProducts -[#green]-> DB_payment_products : JPA/ORM (CRUD)

' Légende (optionnelle)
legend right
  <b>Bleu</b> : Communication HTTP/REST depuis le client front end
  <b>Orange</b> : Communication HTTP/REST entre container dockerisés
  <b>Vert</b> : Accès base de données
  <b>CRUD</b> : CreateReadUpdateDelete
endlegend

@enduml